/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactosRouteImport } from './routes/contactos'
import { Route as ConteudosRouteImport } from './routes/conteudos'
import { Route as FinSummitRouteImport } from './routes/fin-summit'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ProgramasRouteImport } from './routes/programas'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ConteudosIndexRouteImport } from './routes/conteudos.index'
import { Route as ConteudosNewsletterRouteImport } from './routes/conteudos.newsletter'
import { Route as ConteudosPodcastRouteImport } from './routes/conteudos.podcast'
import { Route as SobreIndexRouteImport } from './routes/sobre.index'
import { Route as SobreEquipaRouteImport } from './routes/sobre.equipa'
import { Route as SobreEuclidesFranciscoRouteImport } from './routes/sobre.euclides-francisco'
import { Route as ConteudosArtigosIndexRouteImport } from './routes/conteudos.artigos.index'
import { Route as ConteudosArtigosSlugRouteImport } from './routes/conteudos.artigos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactosRoute = ContactosRouteImport.update({
  id: '/contactos',
  path: '/contactos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosRoute = ConteudosRouteImport.update({
  id: '/conteudos',
  path: '/conteudos',
  getParentRoute: () => rootRouteImport,
} as any)
const FinSummitRoute = FinSummitRouteImport.update({
  id: '/fin-summit',
  path: '/fin-summit',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasRoute = ProgramasRouteImport.update({
  id: '/programas',
  path: '/programas',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosIndexRoute = ConteudosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConteudosRoute,
} as any)
const ConteudosNewsletterRoute = ConteudosNewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => ConteudosRoute,
} as any)
const ConteudosPodcastRoute = ConteudosPodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => ConteudosRoute,
} as any)
const SobreIndexRoute = SobreIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SobreRoute,
} as any)
const SobreEquipaRoute = SobreEquipaRouteImport.update({
  id: '/equipa',
  path: '/equipa',
  getParentRoute: () => SobreRoute,
} as any)
const SobreEuclidesFranciscoRoute = SobreEuclidesFranciscoRouteImport.update({
  id: '/euclides-francisco',
  path: '/euclides-francisco',
  getParentRoute: () => SobreRoute,
} as any)
const ConteudosArtigosIndexRoute = ConteudosArtigosIndexRouteImport.update({
  id: '/artigos/',
  path: '/artigos/',
  getParentRoute: () => ConteudosRoute,
} as any)
const ConteudosArtigosSlugRoute = ConteudosArtigosSlugRouteImport.update({
  id: '/artigos/$slug',
  path: '/artigos/$slug',
  getParentRoute: () => ConteudosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contactos': typeof ContactosRoute
  '/conteudos': typeof ConteudosRouteWithChildren
  '/fin-summit': typeof FinSummitRoute
  '/privacidade': typeof PrivacidadeRoute
  '/programas': typeof ProgramasRoute
  '/sobre': typeof SobreRouteWithChildren
  '/termos': typeof TermosRoute
  '/conteudos/newsletter': typeof ConteudosNewsletterRoute
  '/conteudos/podcast': typeof ConteudosPodcastRoute
  '/sobre/equipa': typeof SobreEquipaRoute
  '/sobre/euclides-francisco': typeof SobreEuclidesFranciscoRoute
  '/conteudos/': typeof ConteudosIndexRoute
  '/sobre/': typeof SobreIndexRoute
  '/conteudos/artigos/$slug': typeof ConteudosArtigosSlugRoute
  '/conteudos/artigos/': typeof ConteudosArtigosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contactos': typeof ContactosRoute
  '/fin-summit': typeof FinSummitRoute
  '/privacidade': typeof PrivacidadeRoute
  '/programas': typeof ProgramasRoute
  '/termos': typeof TermosRoute
  '/conteudos/newsletter': typeof ConteudosNewsletterRoute
  '/conteudos/podcast': typeof ConteudosPodcastRoute
  '/sobre/equipa': typeof SobreEquipaRoute
  '/sobre/euclides-francisco': typeof SobreEuclidesFranciscoRoute
  '/conteudos': typeof ConteudosIndexRoute
  '/sobre': typeof SobreIndexRoute
  '/conteudos/artigos/$slug': typeof ConteudosArtigosSlugRoute
  '/conteudos/artigos': typeof ConteudosArtigosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contactos': typeof ContactosRoute
  '/conteudos': typeof ConteudosRouteWithChildren
  '/fin-summit': typeof FinSummitRoute
  '/privacidade': typeof PrivacidadeRoute
  '/programas': typeof ProgramasRoute
  '/sobre': typeof SobreRouteWithChildren
  '/termos': typeof TermosRoute
  '/conteudos/newsletter': typeof ConteudosNewsletterRoute
  '/conteudos/podcast': typeof ConteudosPodcastRoute
  '/sobre/equipa': typeof SobreEquipaRoute
  '/sobre/euclides-francisco': typeof SobreEuclidesFranciscoRoute
  '/conteudos/': typeof ConteudosIndexRoute
  '/sobre/': typeof SobreIndexRoute
  '/conteudos/artigos/$slug': typeof ConteudosArtigosSlugRoute
  '/conteudos/artigos/': typeof ConteudosArtigosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contactos'
    | '/conteudos'
    | '/fin-summit'
    | '/privacidade'
    | '/programas'
    | '/sobre'
    | '/termos'
    | '/conteudos/newsletter'
    | '/conteudos/podcast'
    | '/sobre/equipa'
    | '/sobre/euclides-francisco'
    | '/conteudos/'
    | '/sobre/'
    | '/conteudos/artigos/$slug'
    | '/conteudos/artigos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contactos'
    | '/fin-summit'
    | '/privacidade'
    | '/programas'
    | '/termos'
    | '/conteudos/newsletter'
    | '/conteudos/podcast'
    | '/sobre/equipa'
    | '/sobre/euclides-francisco'
    | '/conteudos'
    | '/sobre'
    | '/conteudos/artigos/$slug'
    | '/conteudos/artigos'
  id:
    | '__root__'
    | '/'
    | '/contactos'
    | '/conteudos'
    | '/fin-summit'
    | '/privacidade'
    | '/programas'
    | '/sobre'
    | '/termos'
    | '/conteudos/newsletter'
    | '/conteudos/podcast'
    | '/sobre/equipa'
    | '/sobre/euclides-francisco'
    | '/conteudos/'
    | '/sobre/'
    | '/conteudos/artigos/$slug'
    | '/conteudos/artigos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactosRoute: typeof ContactosRoute
  ConteudosRoute: typeof ConteudosRouteWithChildren
  FinSummitRoute: typeof FinSummitRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProgramasRoute: typeof ProgramasRoute
  SobreRoute: typeof SobreRouteWithChildren
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contactos': {
      id: '/contactos'
      path: '/contactos'
      fullPath: '/contactos'
      preLoaderRoute: typeof ContactosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos': {
      id: '/conteudos'
      path: '/conteudos'
      fullPath: '/conteudos'
      preLoaderRoute: typeof ConteudosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fin-summit': {
      id: '/fin-summit'
      path: '/fin-summit'
      fullPath: '/fin-summit'
      preLoaderRoute: typeof FinSummitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas': {
      id: '/programas'
      path: '/programas'
      fullPath: '/programas'
      preLoaderRoute: typeof ProgramasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/': {
      id: '/conteudos/'
      path: '/'
      fullPath: '/conteudos/'
      preLoaderRoute: typeof ConteudosIndexRouteImport
      parentRoute: typeof ConteudosRoute
    }
    '/conteudos/newsletter': {
      id: '/conteudos/newsletter'
      path: '/newsletter'
      fullPath: '/conteudos/newsletter'
      preLoaderRoute: typeof ConteudosNewsletterRouteImport
      parentRoute: typeof ConteudosRoute
    }
    '/conteudos/podcast': {
      id: '/conteudos/podcast'
      path: '/podcast'
      fullPath: '/conteudos/podcast'
      preLoaderRoute: typeof ConteudosPodcastRouteImport
      parentRoute: typeof ConteudosRoute
    }
    '/sobre/': {
      id: '/sobre/'
      path: '/'
      fullPath: '/sobre/'
      preLoaderRoute: typeof SobreIndexRouteImport
      parentRoute: typeof SobreRoute
    }
    '/sobre/equipa': {
      id: '/sobre/equipa'
      path: '/equipa'
      fullPath: '/sobre/equipa'
      preLoaderRoute: typeof SobreEquipaRouteImport
      parentRoute: typeof SobreRoute
    }
    '/sobre/euclides-francisco': {
      id: '/sobre/euclides-francisco'
      path: '/euclides-francisco'
      fullPath: '/sobre/euclides-francisco'
      preLoaderRoute: typeof SobreEuclidesFranciscoRouteImport
      parentRoute: typeof SobreRoute
    }
    '/conteudos/artigos/': {
      id: '/conteudos/artigos/'
      path: '/artigos'
      fullPath: '/conteudos/artigos/'
      preLoaderRoute: typeof ConteudosArtigosIndexRouteImport
      parentRoute: typeof ConteudosRoute
    }
    '/conteudos/artigos/$slug': {
      id: '/conteudos/artigos/$slug'
      path: '/artigos/$slug'
      fullPath: '/conteudos/artigos/$slug'
      preLoaderRoute: typeof ConteudosArtigosSlugRouteImport
      parentRoute: typeof ConteudosRoute
    }
  }
}

interface ConteudosRouteChildren {
  ConteudosNewsletterRoute: typeof ConteudosNewsletterRoute
  ConteudosPodcastRoute: typeof ConteudosPodcastRoute
  ConteudosIndexRoute: typeof ConteudosIndexRoute
  ConteudosArtigosSlugRoute: typeof ConteudosArtigosSlugRoute
  ConteudosArtigosIndexRoute: typeof ConteudosArtigosIndexRoute
}

const ConteudosRouteChildren: ConteudosRouteChildren = {
  ConteudosNewsletterRoute: ConteudosNewsletterRoute,
  ConteudosPodcastRoute: ConteudosPodcastRoute,
  ConteudosIndexRoute: ConteudosIndexRoute,
  ConteudosArtigosSlugRoute: ConteudosArtigosSlugRoute,
  ConteudosArtigosIndexRoute: ConteudosArtigosIndexRoute,
}

const ConteudosRouteWithChildren = ConteudosRoute._addFileChildren(
  ConteudosRouteChildren,
)

interface SobreRouteChildren {
  SobreEquipaRoute: typeof SobreEquipaRoute
  SobreEuclidesFranciscoRoute: typeof SobreEuclidesFranciscoRoute
  SobreIndexRoute: typeof SobreIndexRoute
}

const SobreRouteChildren: SobreRouteChildren = {
  SobreEquipaRoute: SobreEquipaRoute,
  SobreEuclidesFranciscoRoute: SobreEuclidesFranciscoRoute,
  SobreIndexRoute: SobreIndexRoute,
}

const SobreRouteWithChildren = SobreRoute._addFileChildren(SobreRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactosRoute: ContactosRoute,
  ConteudosRoute: ConteudosRouteWithChildren,
  FinSummitRoute: FinSummitRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProgramasRoute: ProgramasRoute,
  SobreRoute: SobreRouteWithChildren,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
